### ISSUE TITLE
User-Authentication

### ISSUE THREAD

**Issue by ThomasEverding** [open-pioneer/trails-openlayers-base-packages#39]
The user needs to be authenticated, an anonymous app access is not allowed.
The authentication backend uses a keycloak server.
The authentication shall use the OpenID connect authentication flow: https://openid.net/developers/how-connect-works/

Other components need access to user details such as assigned rights and/or roles.

Acceptance criteria:
 - [x] The app recognized not-authenticated users and automatically starts the authentication flow. (see #99)
 - [x] The OpenID connect authentication flow is implemented.
 - [x] An unauthenticated app access is prohibited (client-side security) (see #99)
 - [x] The URL(s) of the keycloak server endpoint(s) can be configured.
 - [ ] ~~The name of the current user is displayed in the app. (retrievable via #99)~~
 - [ ] ~~The app contains a logout-control. (implementable via #99)~~
 - [x] Other components can access the user details. (see #99)
 - [x] #308

Investigation needed:
- Login: What happens if the user is already logged in Keycloak (automatic login)? --> User is automatically logged in (or standard process)
- Logout: Can a client-side application trigger global logout (i.e. invalidate token and Keycloak-session)? --> also invalidate Keycloak Session 
- Login/Logout: What happens if the user opens the app in multiple tabs? --> no explicit handling
- Token-Storage: Where should the token be stored (session storage, local storage)? --> not relevant

Reference documentation: 
https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter

out of scope:
- sec.man integration (or other potential ID providers)
- other authentication flows than OpenID connect
- mixed app access (anonymous or authenticated)
- access to the user profile / password update funtions
- embedded applications
